opt_in_rules:
  - force_unwrapping

disabled_rules:
  - line_length

included:
  - PlaygroundBook/Sources
  - LiveViewTestApp
  - TortoiseGraphicsTests

identifier_name:
  excluded:
    - 🐢
    - 🐇
    - x
    - y
    - r
    - g
    - b

force_cast: warning
